### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by mathewhauer** [mathewhauer/iTFR#2]
@schmert 
- [ ] Edit one last time

@mathewhauer
- [x] Submit to PAA April 6 2018
- [ ] Possibly send to outside reviewers prior to peer review submittal
- [ ] Submit to a journal
